# Generated by Django 3.1.3 on 2020-11-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='profile_pic/'),
        ),
    ]
